### ISSUE TITLE
1.8 version breaks Forge b1405 on Dedicated Server Startup

### ISSUE THREAD

**Issue by kreezxil** [lumien231/Random-Things#1]
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:483)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getDeclaredMethods0(Native Method)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getMethod0(Class.java:3010)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getMethod(Class.java:1776)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 6 more
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 13 more
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer lumien.randomthings.asm.ClassTransformer@4a1e3ac1 from coremod LoadingPlugin
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 15 more
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.ClassWriter.a(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.Frame.a(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.Frame.a(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at lumien.randomthings.asm.ClassTransformer.patchWorldClass(ClassTransformer.java:691)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at lumien.randomthings.asm.ClassTransformer.transform(ClassTransformer.java:44)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
[10:38:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 17 more

**Comment by kreezxil** [comment]
Would like to point out that the same exact error happens with the new b1409 that came out this afternoon

**Comment by lumien231** [comment]
Yeah, Forge changed something that requires a little change in all coremods, going to fix this next version.

**Comment by kreezxil** [comment]
How soon till the next version? I've stopped updating my forge because I use PerfectSpawn for one. I also use RandomThings ...
