### ISSUE TITLE
Crash with placement preview

### ISSUE THREAD

**Issue by medsal15** [lumien231/Random-Things#109]
As the name says, placement preview lets you see how the block you are about to place will be placed. Which doesn't appear to work well with light redirectors.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-49.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 07.08.16 07:15
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at lumien.randomthings.block.BlockLightRedirector.func_180663_b(BlockLightRedirector.java:38)
    at fi.dy.masa.placementpreview.fake.FakeChunk.setBlockState(FakeChunk.java:68)
    at fi.dy.masa.placementpreview.fake.FakeWorld.setBlockState(FakeWorld.java:166)
    at fi.dy.masa.placementpreview.event.TickHandler.copyCurrentBlocksToFakeWorld(TickHandler.java:255)
    at fi.dy.masa.placementpreview.event.TickHandler.checkAndUpdateBlocks(TickHandler.java:163)
    at fi.dy.masa.placementpreview.event.TickHandler.onClientTick(TickHandler.java:84)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_205_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at lumien.randomthings.block.BlockLightRedirector.func_180663_b(BlockLightRedirector.java:38)
    at fi.dy.masa.placementpreview.fake.FakeChunk.setBlockState(FakeChunk.java:68)
    at fi.dy.masa.placementpreview.fake.FakeWorld.setBlockState(FakeWorld.java:166)
    at fi.dy.masa.placementpreview.event.TickHandler.copyCurrentBlocksToFakeWorld(TickHandler.java:255)
    at fi.dy.masa.placementpreview.event.TickHandler.checkAndUpdateBlocks(TickHandler.java:163)
    at fi.dy.masa.placementpreview.event.TickHandler.onClientTick(TickHandler.java:84)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_205_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['medsal15'/86, l='MpServer', x=87.53, y=4.00, z=1159.30]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (86,4,1136), Chunk: (at 6,0,0 in 5,71; contains blocks 80,0,1136 to 95,255,1151), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
    Level time: 337640 game time, 337640 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 71 total; [EntityHorse['Horse'/10, l='MpServer', x=60.06, y=4.00, z=1202.11], EntityWallpaper['entity.grimpack.Wallpaper.name'/12, l='MpServer', x=79.50, y=4.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/13, l='MpServer', x=79.50, y=5.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/14, l='MpServer', x=78.50, y=5.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/15, l='MpServer', x=78.50, y=4.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/16, l='MpServer', x=77.50, y=4.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/17, l='MpServer', x=77.50, y=5.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/18, l='MpServer', x=76.50, y=5.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/19, l='MpServer', x=76.50, y=4.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/20, l='MpServer', x=75.50, y=4.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/21, l='MpServer', x=75.50, y=5.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/22, l='MpServer', x=74.50, y=5.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/23, l='MpServer', x=74.50, y=4.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/24, l='MpServer', x=73.50, y=6.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/25, l='MpServer', x=74.50, y=6.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/26, l='MpServer', x=74.50, y=7.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/27, l='MpServer', x=73.50, y=7.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/28, l='MpServer', x=75.50, y=6.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/29, l='MpServer', x=75.50, y=7.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/30, l='MpServer', x=76.50, y=6.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/31, l='MpServer', x=76.50, y=7.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/32, l='MpServer', x=77.50, y=6.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/33, l='MpServer', x=78.50, y=6.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/34, l='MpServer', x=78.50, y=7.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/35, l='MpServer', x=77.50, y=7.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/36, l='MpServer', x=74.50, y=8.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/37, l='MpServer', x=75.50, y=8.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/38, l='MpServer', x=74.50, y=9.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/39, l='MpServer', x=75.50, y=9.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/40, l='MpServer', x=76.50, y=8.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/41, l='MpServer', x=76.50, y=9.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/42, l='MpServer', x=77.50, y=8.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/43, l='MpServer', x=77.50, y=9.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/44, l='MpServer', x=78.50, y=8.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/45, l='MpServer', x=78.50, y=9.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/46, l='MpServer', x=79.50, y=8.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/47, l='MpServer', x=79.50, y=9.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/48, l='MpServer', x=73.50, y=10.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/49, l='MpServer', x=74.50, y=10.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/50, l='MpServer', x=73.50, y=11.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/51, l='MpServer', x=74.50, y=11.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/52, l='MpServer', x=75.50, y=10.50, z=1148.03], EntityWallpaper['entity.grimpack.Wallpaper.name'/53, l='MpServer', x=75.50, y=11.50, z=1148.03], EntityDummy['entity.testdummy.Dummy.name'/54, l='MpServer', x=93.50, y=4.00, z=1135.50], EntityDummy['entity.testdummy.Dummy.name'/55, l='MpServer', x=91.50, y=4.00, z=1137.50], EntityDummy['entity.testdummy.Dummy.name'/56, l='MpServer', x=91.50, y=4.00, z=1139.50], EntityDummy['entity.testdummy.Dummy.name'/57, l='MpServer', x=90.50, y=4.00, z=1143.50], EntityDummy['entity.testdummy.Dummy.name'/58, l='MpServer', x=93.50, y=4.00, z=1143.50], EntityDummy['entity.testdummy.Dummy.name'/59, l='MpServer', x=92.50, y=4.00, z=1143.50], EntityDummy['entity.testdummy.Dummy.name'/60, l='MpServer', x=95.50, y=4.00, z=1139.50], EntityDummy['entity.testdummy.Dummy.name'/61, l='MpServer', x=93.50, y=4.00, z=1138.50], EntityDummy['entity.testdummy.Dummy.name'/62, l='MpServer', x=94.50, y=4.00, z=1137.50], EntityDummy['entity.testdummy.Dummy.name'/63, l='MpServer', x=91.50, y=1.00, z=1140.50], EntityDummy['entity.testdummy.Dummy.name'/64, l='MpServer', x=91.50, y=1.00, z=1138.50], EntityDummy['entity.testdummy.Dummy.name'/65, l='MpServer', x=94.50, y=1.00, z=1141.50], EntityDummy['entity.testdummy.Dummy.name'/66, l='MpServer', x=93.50, y=4.00, z=1145.50], EntityDummy['entity.testdummy.Dummy.name'/67, l='MpServer', x=88.50, y=4.00, z=1145.50], EntityDummy['entity.testdummy.Dummy.name'/68, l='MpServer', x=84.50, y=4.00, z=1141.50], EntityDummy['entity.testdummy.Dummy.name'/69, l='MpServer', x=98.50, y=4.00, z=1135.50], EntityDummy['entity.testdummy.Dummy.name'/70, l='MpServer', x=96.50, y=4.00, z=1143.50], EntityDummy['entity.testdummy.Dummy.name'/71, l='MpServer', x=96.50, y=4.00, z=1138.50], EntityDummy['entity.testdummy.Dummy.name'/72, l='MpServer', x=96.50, y=1.00, z=1139.50], EntityDummy['entity.testdummy.Dummy.name'/73, l='MpServer', x=98.50, y=4.00, z=1140.50], EntityDummy['entity.testdummy.Dummy.name'/74, l='MpServer', x=98.50, y=4.00, z=1145.50], EntityFrame['entity.grimpack.Frames.name'/75, l='MpServer', x=101.50, y=6.00, z=1164.03], EntityFrame['entity.grimpack.Frames.name'/76, l='MpServer', x=105.03, y=7.00, z=1162.00], EntityFrame['entity.grimpack.Frames.name'/77, l='MpServer', x=105.03, y=7.00, z=1159.00], EntityFrame['entity.grimpack.Frames.name'/78, l='MpServer', x=97.97, y=11.00, z=1162.00], EntityFrame['entity.grimpack.Frames.name'/79, l='MpServer', x=97.97, y=11.00, z=1159.00], EntitySheep['Sheep'/80, l='MpServer', x=109.23, y=4.00, z=1221.27], EntityPlayerSP['medsal15'/86, l='MpServer', x=87.53, y=4.00, z=1159.30]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1088854320 bytes (1038 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2043 69 mods loaded, 69 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2043.jar) 
    UCHIJAAAA   Forge{12.18.1.2043} [Minecraft Forge](forge-1.10.2-12.18.1.2043.jar) 
    UCHIJAAAA   actuallyadditions{1.10.2-r57} [Actually Additions](ActuallyAdditions-1.10.2-r57.jar) 
    UCHIJAAAA   alt{1.05} [Additional Loot Tables](AdditionalLootTables_1.9.4-1.05.jar) 
    UCHIJAAAA   adobeblocks{6.0.2.17} [Adobe Blocks 2](AdobeBlocks-Forge-6.0.2.17.jar) 
    UCHIJAAAA   advancedswords{1.3.0} [Advanced Swords](advancedswords-1.3.0-[1.9.4].jar) 
    UCHIJAAAA   advancedaddons{1.1.0} [Advanced Addons](advancedaddons-1.1.0-[1.9.4].jar) 
    UCHIJAAAA   basemetals{2.3.2} [Base Metals](BaseMetals_1.9.4-2.3.2.6.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   Bullseye{1.0.3} [Bullseye](Bullseye-1.9.4-1.0.3.jar) 
    UCHIJAAAA   cyclopscore{0.7.3} [Cyclops Core](CyclopsCore-1.9.4-0.7.3.jar) 
    UCHIJAAAA   colossalchests{1.3.8} [Colossal Chests](ColossalChests-1.9.4-1.3.8.jar) 
    UCHIJAAAA   cosmeticarmorreworked{1.10.2-v1a} [CosmeticArmorReworked](CosmeticArmorReworked-1.10.2-v1a.jar) 
    UCHIJAAAA   Ding{MC1.9.0v2} [Ding](Ding-1.10.2-1.0.0.jar) 
    UCHIJAAAA   poweradvantage{2.2.1} [Power Advantage](PowerAdvantage_1.9.4-2.2.1.jar) 
    UCHIJAAAA   electricadvantage{2.1.0} [Electric Advantage](ElectricAdvantage_1.9-2.1.0.jar) 
    UCHIJAAAA   enderutilities{0.6.5-beta.2} [Ender Utilities](enderutilities-1.10.2-0.6.5-beta.2.jar) 
    UCHIJAAAA   evilcraft{0.10.7} [EvilCraft](EvilCraft-1.9.4-0.10.7.jar) 
    UCHIJAAAA   extraalchemy{0.2.6.3-beta} [Extra Alchemy](extraalchemy-0.2.6.3-beta.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCHIJAAAA   frt{6.3.2.22} [Fire's Random Things](FiresRandomThings-Forge-6.3.2.22.jar) 
    UCHIJAAAA   JEI{3.7.9.236} [Just Enough Items](jei_1.10.2-3.7.9.236.jar) 
    UCHIJAAAA   FloodLights{1.2.7-145} [Flood Lights](FloodLights-1.9.4-1.2.7-145.jar) 
    UCHIJAAAA   fluxducts{1.0.4} [Flux Ducts](fluxducts-mc1.9.4-1.0.4.jar) 
    UCHIJAAAA   substratum{1.7.0.0} [Substratum](Substratum-1.10.2-1.7.0.0.jar) 
    UCHIJAAAA   foundry{2.0.0.1} [Foundry](Foundry-1.10.2-2.0.0.1.jar) 
    UCHIJAAAA   ftfragileglass{1.8.1} [Fragile Glass and Thin Ice](Fragile Glass and Thin Ice 1.10.2-1.8.1.jar) 
    UCHIJAAAA   SilentLib{1.0.12} [Silent Lib](SilentLib-1.9.4-1.0.12-20.jar) 
    UCHIJAAAA   FunOres{1.3.0} [Fun Ores](FunOres-1.9.4-1.3.0-73 %28server hotfix%29.jar) 
    UCHIJAAAA   harvestchevsky{b8} [Gentle Harvest](Gentle_Harvest_1.9_b8.jar) 
    UCHIJAAAA   giacomosfoundry{1.3.5} [Giacomo's Foundry](GiacomosFoundry1.10.2-1.3.5.jar) 
    UCHIJAAAA   grimpack{3.2.2.8} [Grim Pack](Grim Pack-1.10.2-3.2.2.8.jar) 
    UCHIJAAAA   InventoryPets{1.4.8.1} [Inventory Pets](inventorypets-1.10-1.4.8.1.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.9.796} [Iron Chest](ironchest-1.10.2-7.0.9.796.jar) 
    UCHIJAAAA   jeresources{0.4.6.42} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.6.42.jar) 
    UCHIJAAAA   jwin{univ_compat_filler} [Just What I Needed](jwin-0.12.0_mc1.10.2.jar) 
    UCHIJAAAA   lightningcraft{2.4.4} [LightningCraft](lightningcraft-2.4.4.jar) 
    UCHIJAAAA   lucky{7.3.0} [Lucky Block](LuckyBlock_1-10-2_v7-3-0.zip) 
    UCHIJAAAA   mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
    UCHIJAAAA   testdummy{1.11} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UCHIJAAAA   modernmetals{0.11.0} [Modern Metals](ModernMetals-0.11.0.jar) 
    UCHIJAAAA   moreanvils{6.0.2.11} [More Anvils](MoreAnvils-Forge-6.0.2.11.jar) 
    UCHIJAAAA   nethercore{1.10.2-2.0.2} [Nether Core](nethercore-1.10.2-2.0.2.jar) 
    UCHIJAAAA   fodc{1.9.1} [Ore Dictionary Converter](OreDictionaryConverter-1.9.1.jar) 
    UCHIJAAAA   orespawn{1.0.3} [Ore Spawn](OreSpawn_1.9.4-1.0.3.jar) 
    UCHIJAAAA   placementpreview{0.2.0} [Placement Preview](placementpreview-1.10.2-0.2.0.jar) 
    UCHIJAAAA   packchevsky{b6} [Potion Packs](PotionPacks_1.10_b6.jar) 
    UCHIJAAAA   Psi{r1.0-37} [Psi](Psi-r1.0-37.jar) 
    UCHIJAAAA   psionup{GRADLE:VERSION.GRADLE:BUILD} [PSIonic Upgrades](PSIonicUpgrades-r1.13.jar) 
    UCHIJAAAA   Quark{beta-49} [Quark](Quark-beta-49.jar) 
    UCHIJAAAA   randomthings{3.7.5} [Random Things](RandomThings-MC1.10.2-3.7.5.jar) 
    UCHIJAAAA   refinedrelocation{@VERSION@} [Refined Relocation](RefinedRelocation-mc1.10.2-2.0.8.jar) 
    UCHIJAAAA   xreliquary{1.10.2-1.3.3.455} [Reliquary](Reliquary-1.10.2-1.3.3.455.jar) 
    UCHIJAAAA   AS_Ruins{16.2} [Ruins Spawning System](Ruins-1.10.2.jar) 
    UCHIJAAAA   corn{1.1} [Corn Crop Mod](SimpleCorn1.10-1.1.jar) 
    UCHIJAAAA   steamadvantage{2.1.0} [Steam Advantage](SteamAdvantage_1.9.4-2.1.0.jar) 
    UCHIJAAAA   tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJAAAA   thutcore{4.0.0} [ThutCore](thutcore-1.10.2-4.0.0.jar) 
    UCHIJAAAA   thuttech{3.0.9} [Thut's Tech](thuttech-3.0.9.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   tinker_io{release 2.3.3} [Tinker I/O](tinker_io-1.10.2-release 2.3.3.jar) 
    UCHIJAAAA   Torcherino{4.2s} [Torcherino](Torcherino-4.2s.jar) 
    UCHIJAAAA   underphangables{1.0.2} [Underp Hangables](underphangables-1.10.2-1.0.2.jar) 
    UCHIJAAAA   va{1.10.2-1.0} [Vanilla Automation](va-1.10.2-1.0.jar) 
    UCHIJAAAA   vanillamagic{1.10.2-0.10.1.0} [Vanilla Magic](vanillamagic-1.10.2-0.10.1.0.jar) 
    UCHIJAAAA   VTweaks{1.4.9.5} [V-Tweaks](VTweaks-1.10.x-1.4.9.5.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    UCHIJAAAA   waterstrainer{1.0.2} [Water Strainer](WaterStrainer-1.9.4-1.0.2.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-49.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)

```
Launched Version: 1.10.2-forge1.10.2-12.18.1.2043
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Pentium(R) CPU N3530 @ 2.16GHz
```

**Comment by medsal15** [comment]
Possibly fixed on the other side. Closing it.
