### ISSUE TITLE
[1.7.10] [LATEST] Crash with star miner!

### ISSUE THREAD

**Issue by elix-x** [lumien231/Random-Things#111]
Wll it is not completely a crash... IT'S WORSE!
Game just doesn't launch:
log:
```
[14:09:25] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:09:25] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:09:25] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[14:09:25] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[14:09:25] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_25
[14:09:25] [main/WARN] [FML]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:25] [main/INFO] [FML]: [AppEng] Core Init
[14:09:25] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:25] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:25] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:25] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:09:26] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:09:26] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:09:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:09:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:09:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:09:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:09:27] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:27] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [IC2-core]: Loaded library ejml-0.23.jar.
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:28] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:104]: Successfully Registered Transformer
[14:09:29] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:297]: [Micdoodle8Core]: Patching game...
[14:09:29] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:297]: [Micdoodle8Core]: Patching game...
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:09:29] [main/INFO] [STDOUT]: [cofh.asm.PCCAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[14:09:29] [main/INFO] [STDOUT]: [cofh.asm.PCCAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[14:09:29] [main/INFO] [STDOUT]: [cofh.asm.PCCAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[14:09:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:30] [main/INFO] [malisiscore]: Hook registered for net.minecraft.client.Minecraft
[14:09:30] [main/INFO] [malisiscore]: Hook registered for net.minecraft.client.multiplayer.PlayerControllerMP
[14:09:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:09:30] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[14:09:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[14:09:30] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:09:30] [main/INFO] [battlegear2]: M&B - Patching Class Minecraft (bao)
[14:09:30] [main/INFO] [battlegear2]: 	Patching method Click Mouse in Minecraft
[14:09:30] [main/INFO] [battlegear2]: M&B - Patching Class Minecraft done
[14:09:30] [main/INFO] [malisiscore]: Found hooks for net.minecraft.client.Minecraft (bao)
[14:09:30] [main/INFO] [battlegear2]: M&B - Patching Class EntityPlayer (yz)
[14:09:30] [main/INFO] [battlegear2]: 	Adding new fields to EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: 	Patching constructor in EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: 	Patching method entityInit in EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: 	Patching method onUpdate in EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: 	Patching method onItemUseFinish in EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: 	Patching method setCurrentItemOrArmor in EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: 	Creating new methods in EntityPlayer
[14:09:30] [main/INFO] [battlegear2]: M&B - Patching Class EntityPlayer done
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Target method found : EntityPlayer.moveEntityWithHeading
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to EntityPlayer.moveEntityWithHeading
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Target method found : EntityPlayer.getPosition
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to EntityPlayer.getPosition
[14:09:30] [main/INFO] [FML]: [OpenBlocks] Trying to patch EntityPlayer.isInBed (class: yz)
[14:09:30] [main/INFO] [FML]: [OpenBlocks] isInBed patch applied. Enabling sleeping bags
[14:09:30] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1764]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[14:09:30] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1764]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Target method found : Entity.onEntityUpdate
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to Entity.onEntityUpdate
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Target method found : EntityPlayerSP.onLivingUpdate
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to EntityPlayerSP.onLivingUpdate(A)
[14:09:30] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to EntityPlayerSP.onLivingUpdate(B)
[14:09:31] [main/INFO] [OpenMods]: openmods.OpenModsClassTransformer$2.createVisitor(OpenModsClassTransformer.java:34): Trying to apply movement callback (class: blk)
[14:09:31] [main/INFO] [OpenMods]: openmods.movement.MovementPatcher$CallInjector.visitMethodInsn(MovementPatcher.java:70): Callback inserted. Using new movement handler.
[14:09:31] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to World.<init>
[14:09:31] [main/INFO] [LaunchWrapper]: [Starminer]Injected additional code to World.<init>
[14:09:31] [main/INFO] [RandomThingsCore]: Found World Class: net/minecraft/world/World
[14:09:31] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassFormatError: Duplicate field name&signature in class file net/minecraft/world/World
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more

```

When i remove random things or star miner, everything works...

**Comment by clienthax** [comment]
seems random things and star miner are trying to modify the same class and end up conflicting

**Comment by lumien231** [comment]
Yes but the modifications i'm making shouldn't cause conflicts: https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/Transformer/RTClassTransformer.java#L159-L232
