### ISSUE TITLE
1.7.10 Crash on startup

### ISSUE THREAD

**Issue by Glockshna** [lumien231/Random-Things#118]
Not much to report other than the game crashes on startup when I install Random Things. Something to do with leaves.

[08:06:09] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:06:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:06:09] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[08:06:09] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[08:06:09] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_40
[08:06:09] [main/INFO] [FML]: [AppEng] Core Init
[08:06:09] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of ForgeMultipart, 1.1.2.331 is newer than request 1.1.0.309
[08:06:10] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod redgear.geocraft.core.MinableTransformer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod redgear.core.asm.CoreLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:06:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:06:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:06:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:06:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:06:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[08:06:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [STDERR]: [redgear.geocraft.codechicken.DepLoader$DepLoadInst:checkExisting:437]: Warning: version of ForgeMultipart, 1.1.2.331 is newer than request 1.1.0.309
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [OpenMods]: openmods.config.simple.ConfigProcessor.process(ConfigProcessor.java:73): Parsing config file 'C:\Games\Minecraft\1.7.10 New\LP MP\.minecraft\config\OpenModsLibCore.json'
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:06:11] [main/INFO] [STDOUT]: [cofh.asm.PCCAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[08:06:11] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.11.jar:?]
	at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32) [forge-1.7.10-10.13.2.1291.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	... 6 more
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:06:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[08:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[08:06:11] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[08:06:12] [main/INFO] [FML]: [bettersleeping] Successfully patched yz with class cz.ondraster.bettersleeping.asm.patches.PatchIsDay
[08:06:12] [main/INFO] [FML]: [bettersleeping] Successfully patched yz with class cz.ondraster.bettersleeping.asm.patches.PatchIsInBed
[08:06:12] [main/INFO] [FML]: [OpenBlocks] Trying to patch EntityPlayer.isInBed (class: yz)
[08:06:12] [main/INFO] [FML]: [OpenBlocks] isInBed patch applied. Enabling sleeping bags
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Patching class net.minecraft.entity.player.EntityPlayer
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Successfully applied GUIEVENT ASM handler 1!
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Successfully applied GUIEVENT ASM handler 2!
[08:06:12] [main/INFO] [OpenMods]: openmods.core.OpenModsClassTransformer$2$1.createVisitor(OpenModsClassTransformer.java:115): Trying to apply movement callback (class: blk)
[08:06:12] [main/INFO] [OpenMods]: openmods.movement.MovementPatcher$CallInjector.visitMethodInsn(MovementPatcher.java:66): Callback inserted. Using new movement handler.
[08:06:12] [main/INFO] [MobiusCore]: Current code is OBFUSCATED
[08:06:12] [main/INFO] [MobiusCore]: Found cpw.mods.fml.common.FMLCommonHandler with checksum 8570203264A5FFF09837CAC6FE0103FB
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in onPreServerTick ()V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in onPostServerTick ()V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in onPreWorldTick (Lahb;)V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in onPostWorldTick (Lahb;)V
[08:06:12] [main/INFO] [MobiusCore]: Switching injection mode to FORGE
[08:06:12] [main/INFO] [MobiusCore]: [MobiusCore] Found net.minecraft.world.World [ ahb ] with checksum 5EE4BD7E50549D37788864CE11387F29
[08:06:12] [main/INFO] [MobiusCore]: Found World.updateEntities()...
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[08:06:12] [main/INFO] [MobiusCore]: Found World.<init> (Lazc;Ljava/lang/String;Lahj;Laqo;Lqi;)V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in <init> (Lazc;Ljava/lang/String;Lahj;Laqo;Lqi;)V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in <init> (Lazc;Ljava/lang/String;Lahj;Laqo;Lqi;)V
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Patching class net.minecraft.world.World
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Successfully applied ICECANCEL ASM handler!
[08:06:12] [main/INFO] [RandomThingsCore]: Found World Class: net/minecraft/world/World
[08:06:12] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[08:06:12] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[08:06:12] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Patching class net.minecraft.client.gui.inventory.GuiContainer
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Successfully applied ITEMRENDEREVENT ASM handler!
[08:06:12] [main/INFO] [MobiusCore]: [MobiusCore] Found net.minecraft.world.WorldServer [ mt ] with checksum A9B6290BB23DD7A1659115ABB503DDD8
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in b ()V
[08:06:12] [main/INFO] [MobiusCore]: Successful injection in b ()V
[08:06:12] [main/INFO]: Setting user: Glockshna
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Patching class net.minecraft.entity.item.EntityItem
[08:06:12] [main/INFO] [FML]: DRAGONAPI: Successfully applied ITEMUPDATE ASM handler!
[08:06:12] [main/INFO] [RandomThingsCore]: Found Item Class: net/minecraft/item/Item
[08:06:12] [main/INFO] [<CJB ASM>]: Found Leave Class: aod
[08:06:12] [main/INFO] [RandomThingsCore]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[08:06:12] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockOldLeaf
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockOldLeaf
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockLeaves
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeaves
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockLeavesBase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeavesBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/block/BlockLeavesBase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more

**Comment by lumien231** [comment]
Remove the Fast Leave Decay mod, its included in random things.

**Comment by Glockshna** [comment]
How? That mod doesn't exist in my mods folder. I only see Random Things.

**Comment by lumien231** [comment]
I'm pretty sure you do, if you don't check which mod is conflicting with it.

**Comment by Glockshna** [comment]
Well Fast Leave (Leaf?) Decay Mod doesn't exist in my mods folder and I certainly didn't install it. In fact I installed Random Things primarily for the leaf decay changes it applies. How would I go about finding which mod conflicts other than removing everything one by one?

**Comment by lumien231** [comment]
Remove half of your mods every run and continue that with the one that crashes.

**Comment by Glockshna** [comment]
Not sure who's problem this one is. It's CJB's mod that conflicts. http://cjbmods.com/forums/viewtopic.php?f=4&t=81

Thanks for the help. I had the Xray mod installed to easily test changes to ore generation so it's not a big deal.
