### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by leytilera** [lumien231/Random-Things#120]
at lumien.randomthings.Handler.RTTickHandler.serverTick(RTTickHandler.java:69)
    at lumien.randomthings.Handler.RTTickHandler.tick(RTTickHandler.java:22)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_654_RTTickHandler_tick_TickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Unknown Source)

**Comment by Ryius** [comment]
same problem

**Comment by Ryius** [comment]
do you run 1.7.10 and Random Things + deep resonance
