### ISSUE TITLE
Crash on entering world

### ISSUE THREAD

**Issue by Synize** [lumien231/Random-Things#126]
Not sure if I should reporting this to you, ender
io or rftools.

I have an rftools redstone wireless reciever connected to an enderio conduit in the world when we login it crashes with Caused by: java.lang.ClassCastException: mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity cannot be cast to lumien.randomthings.tileentity.TileEntityRedstoneObserver

[06:39:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ClassCastException: mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity cannot be cast to lumien.randomthings.tileentity.TileEntityRedstoneObserver
at lumien.randomthings.block.BlockRedstoneObserver.func_180656_a(BlockRedstoneObserver.java:50) ~[BlockRedstoneObserver.class:?]
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:375) ~[art$a.class:?]
at net.minecraft.world.World.func_175651_c(World.java:3244) ~[aid.class:?]
at net.minecraft.world.World.func_175687_A(World.java:3258) ~[aid.class:?]
at crazypants.enderio.machine.RedstoneControlMode.isConditionMet(RedstoneControlMode.java:83) ~[RedstoneControlMode.class:?]
at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:278) ~[AbstractMachineEntity.class:?]
at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73) ~[AbstractPoweredMachineEntity.class:?]
at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:417) ~[TileFarmStation.class:?]
at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36) ~[TileEntityBase.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
... 4 more
[06:39:44] [Server thread/ERROR]: This crash report has been saved to: /var/games/minecraft/servers/Fractured/./crash-reports/crash-2016-09-15_06.39.44-server.txt
[06:39:44] [Server thread/INFO]: Stopping server

[crash-2016-09-15_05.23.38-server.txt](https://github.com/lumien231/Random-Things/files/473978/crash-2016-09-15_05.23.38-server.txt)
[crash-2016-09-15_06.39.44-server.txt](https://github.com/lumien231/Random-Things/files/473979/crash-2016-09-15_06.39.44-server.txt)

**Comment by Synize** [comment]
I should have also mentioned i am on forge-1.10.2-12.18.1.2087
Following version of these mods.
EnderCore-1.10.2-0.4.1.54-beta.jar  
EnderIO-1.10.2-3.0.1.107_beta.jar
RandomThings-MC1.10.2-3.7.5.jar 
rftools-1.10-5.22.jar
mcjtylib-1.10-2.0.2.jar
