### ISSUE TITLE
"Duplicate Stat" Crash

### ISSUE THREAD

**Issue by ChaosCron1** [lumien231/Random-Things#196]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MuonPlugin (muon-0.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  GudLib (gud_lib-1.1.0.2.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  PotionCoreFMLLoadingPlugin (PotionCore-1.4_for_1.11.2.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  TerrariaCraftCore (TerrariaCraft_1.11.2-36a.jar)
  LoadingPlugin (CrystalMod-1.11.2-4.5.0dev.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  literalascension (literalascension-1.11.2-1.0.1.1.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  LoadingPlugin (Quark-r1.2-83.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 3/7/17 5:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Random Things (randomthings)
Caused by: java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.spirit.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.spirit.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.spirit
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:42)
	at net.minecraft.stats.StatList.func_151182_a(StatList.java:306)
	at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:412)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerEgg(EntityRegistry.java:220)
	at lumien.randomthings.entitys.ModEntitys.init(ModEntitys.java:18)
	at lumien.randomthings.RandomThings.preInit(RandomThings.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:275)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 483313680 bytes (460 MB) / 1599201280 bytes (1525 MB) up to 7408844800 bytes (7065 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2253 139 mods loaded, 139 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2253.jar) 
	UCH	forge{13.20.0.2253} [Minecraft Forge] (forge-1.11.2-13.20.0.2253.jar) 
	UCH	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCH	gud_lib{1.0.0.1} [GudLib] (gud_lib-1.1.0.2.jar) 
	UCH	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCH	muon{Broken} [Muon] (minecraft.jar) 
	UCH	potioncore_coremod{1.4_for_1.11.2} [Potion Core Coremod] (minecraft.jar) 
	UCH	backpacks16840{3.1.6} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.6.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	dmonsters{1.14} [Deadly Monsters] (1.11.2_deadly_monsters_1.141.jar) 
	UCH	uncraftingtable{1.7.1-pre11} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1-pre11.jar) 
	UCH	jei{4.2.7.241} [Just Enough Items] (jei_1.11.2-4.2.7.241.jar) 
	UCH	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.3.10.jar) 
	UCH	actuallyadditions{1.11.2-r100} [Actually Additions] (ActuallyAdditions-1.11.2-r100.jar) 
	UCH	thinkbigcore{1.6.1} [§5§m===§r §e§lThink Big Core §5§m===§r] (Think Big Core V1.6.1 - 1.11.2.jar) 
	UCH	adinferos{1.2.6} [§e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!!] (Ad Inferos V1.2.6 - 1.11.2.jar) 
	UCH	adobeblocks{7.0.1} [Adobe Blocks 2] (AdobeBlocks-1.11.2-7.0.1.jar) 
	UCH	advancedsticks{1.4.7} [§9Advanced Sticks Mod] (Advanced Sticks 1.11.2 by XxRexRaptorxX (v.1.4.7).jar) 
	UCH	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCH	allomancy{2.5.2} [Allomancy] (allomancy-2.5.2.jar) 
	UCH	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCH	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.11-1.0.5.jar) 
	UCH	appletrees{V1.2} [Apple Trees] (AppleTrees-1.11.2-V1.2.jar) 
	UCH	immcraft{1.2.6} [Immersive Craft] (immcraft-1.1x-1.2.6.jar) 
	UCH	aquamunda{0.0.6beta} [Aqua Munda] (aquamunda-0.0.6beta.jar) 
	UCH	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCH	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.b31.jar) 
	UCH	as_extraresources{1.0.2} [§9AS: §6Extra Resources Add-on] (AS-ExtraResources 1.11.2 by XxRexRaptorxX (v.1.0.2).jar) 
	UCH	ashenwheat{3.2.0.2} [Ashenwheat] (ashenwheat-1.11.2-3.2.0.2.jar) 
	UCH	quark{r1.2-83} [Quark] (Quark-r1.2-83.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling 1.11.2-1.3.5.jar) 
	UCH	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCH	betterwithmods{1.0.1} [Better With Mods] (Better With Mods-1.0.1-1.11.2.jar) 
	UCH	bullseye{2.0.0} [Bullseye] (Bullseye-1.11.2-2.0.0.jar) 
	UCH	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UCH	cyclopscore{0.9.3} [Cyclops Core] (CyclopsCore-1.11.2-0.9.3.jar) 
	UCH	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.1.jar) 
	UCH	convenientadditions{1.1-29} [Convenient Additions] (ConvenientAdditions-1.1-build29.jar) 
	UCH	cosmeticarmorreworked{1.11.2-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1.jar) 
	UCH	eleccore{1.7.409} [ElecCore] (ElecCore-1.11-1.7.409.jar) 
	UCH	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.4.110.jar) 
	UCH	cropdusting{0.6} [CropDusting] (CropDusting-0.6-[1.11.2].jar) 
	UCH	cryingobsidian{1.1.0} [Crying Obsidian] (CryingObsidian-1.11.2-1.1.0.jar) 
	UCH	crystalmod{4.5.0dev} [Crystal Mod] (CrystalMod-1.11.2-4.5.0dev.jar) 
	UCH	customizeddungeonloot{1.0.0} [§eCustomized Dungeon Loot] (Customized Dungeon Loot 1.11.2 (v.1.0.0).jar) 
	UCH	cyclicmagic{1.1.3} [Cyclic] (Cyclic-1.11.2-1.1.3.jar) 
	UCH	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCH	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCH	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCH	earthworks{1.1.1} [Earthworks] (Earthworks-1.11.2-1.1.1.jar) 
	UCH	elementaldimensions{0.1.0} [Elemental Dimensions] (elementaldimensions-0.1.0.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCH	fecm{Alpha} [Elytra Crafting Recipe Mod] (Elytra Crafting Mod-0.0.3.2 - Alpha.jar) 
	UCH	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.11.2-13.20.0.2201.jar) 
	UCH	embers{0.201} [Embers] (embers-0.201.jar) 
	UCH	endercompass{1.2.5.1} [Ender Compass] (EnderCompass-1.11-1.2.5.1.jar) 
	UCH	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UCH	endertanks{1.5.2} [EnderTanks] (endertanks-1.11.0-1.5.2.jar) 
	UCH	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCH	everlastingabilities{1.2.4} [EverlastingAbilities] (EverlastingAbilities-1.11.2-1.2.4.jar) 
	UCH	evilcraft{0.10.20} [EvilCraft] (EvilCraft-1.11.2-0.10.20.jar) 
	UCH	ezwastelands{1.11-1.2} [EzWastelands] (ezwastelands-1.11-1.2.jar) 
	UCH	felling{1.0} [Felling] (felling-1.0.jar) 
	UCH	forgecraft{1.1.12} [Kitsu's Forgecraft] (ForgeCraft-1.1.12.jar) 
	UCH	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCH	silentlib{2.0.0} [Silent Lib] (SilentLib-1.11-2.0.0-36.jar) 
	UCH	funores{1.5.0} [Fun Ores] (FunOres-1.11-1.5.0-97.jar) 
	UCH	limelib{1.4.1} [LimeLib] (limelib-1.11.2-1.4.1.jar) 
	UCH	furnus{1.91} [Furnus] (furnus-1.11.2-1.91.jar) 
	UCH	giacomos_bookshelf{1.1} [Giacomo's Bookshelves Mod] (GiacomosBookshelf-1.11.2-1.1.jar) 
	UCH	fishing{1.4.8} [Fishing Net Mod] (GiacomosFishingNet-1.11.2-1.4.8.jar) 
	UCH	grimpack{4.0.0.0-beta} [Grim Pack] (Grim Pack-1.11.2-4.0.0.0-beta.jar) 
	UCH	grue{1.3.4} [Grue] (Grue-1.11.2-1.3.4.jar) 
	UCH	gud_clear_jukebox{1.0.0.1} [Clear Jukebox] (gud_clear_jukebox-1.0.0.1.jar) 
	UCH	gud_coolers{2.0.0.4} [Coolers] (gud_coolers-2.0.0.4.jar) 
	UCH	gunmod{1.1} [Simple Shotgun] (GunMod-1.1.jar) 
	UCH	hammercore{1.2.8} [Hammer Core] (HammerCore_1.11.2-1.2.8.jar) 
	UCH	hammerz{1.11.2-0.1.4.27} [Hammerz] (hammerz-1.11.2-0.1.4.27.jar) 
	UCH	hcmw{1.0} [Homecraft Mineware] (hcmw-1.11.2-0.2.9-universal.jar) 
	UCH	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCH	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	UCH	infinitefluids{1.1.0} [InfiniteFluids] (infinitefluids-1.11-1.1.0.jar) 
	UCH	integrateddynamics{0.6.8} [Integrated Dynamics] (IntegratedDynamics-1.11.2-0.6.8.jar) 
	UCH	examplemod{1.0} [Example Mod] (IonItems-1.1.1-ALPHA-1.11.jar) 
	UCH	ionitems{1.1.1} [Ion Items] (IonItems-1.1.1-ALPHA-1.11.jar) 
	UCH	justenoughbuttons{1.11.2-1.4.2} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.2.jar) 
	UCH	jeresources{0.6.3.4} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.3.4.jar) 
	UCH	levels{r1.2.4} [Levels] (Levels 2-1.11.2-r1.2.4.jar) 
	UCH	levelup{${version}} [Level Up!] (LevelUp!-0.14.3-1.11.2.jar) 
	UCH	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCH	literalascension{1.11.2-1.0.1.1} [Literal Ascension] (literalascension-1.11.2-1.0.1.1.jar) 
	UCH	crystallium{2.2.1} [Meldexun's Armor+ Mod] (Meldexun'sArmor+Mod-1.11.2-2.2.2.jar) 
	UCH	moreloottables{0.1.2} [More Loot Tables] (moreloottables-1.11.2-0.1.2.jar) 
	UCH	shear{1.1.2} [More Shearables] (MoreShearables1.2.2-1.11.2.jar) 
	UCH	mysticalagriculture{1.4.3} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.3.jar) 
	UCH	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCH	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.11).jar) 
	UCH	packingtape{1.11.0-0.6.1} [Packing Tape] (PackingTape-1.11.0-0.6.1.jar) 
	UCH	platforms{1.3.2} [Platforms] (platforms-1.11.0-1.3.2.jar) 
	UCH	playerstats2{13r} [Player Stats 2] (PlayerStats2_1.11.2-13r.jar) 
	UCH	potioncore{1.4_for_1.11.2} [Potion Core] (PotionCore-1.4_for_1.11.2.jar) 
	UCH	ytgems{1.0} [Potion Gems] (PotionGems-1.11.2-1.0.jar) 
	UCH	roguelike{1.6.4} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.4.jar) 
	UCH	primal{0.3.7} [PrimalCore] (PrimalCore-0.3.7.jar) 
	UCE	randomthings{3.8} [Random Things] (RandomThings-MC1.11.2-3.8.jar) 
	UCH	reccomplex{1.2.9.1} [Recurrent Complex] (RecurrentComplex-1.2.9.1.jar) 
	UCH	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCH	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-63.jar) 
	UCH	rftools{5.86} [RFTools] (rftools-1.1x-5.86.jar) 
	UCH	rftoolscontrol{1.6.5} [RFTools Control] (rftoolsctrl-1.1x-1.6.5.jar) 
	UCH	rftoolsdim{4.54} [RFTools Dimensions] (rftoolsdim-1.1x-4.54.jar) 
	UCH	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCH	rustic{0.0.4} [Rustic] (rustic-0.0.4.jar) 
	UCH	simplecoins{0.6.0} [Simple Coins] (SimpleCoinsMod-1.11.2-1.0.0-Release.jar) 
	UCH	simpleoregen{3.0.1} [Simple Ore Generation] (SimpleOreGeneration v3.0.1 mc1.11.2.jar) 
	UCH	simplyconveyors{2.1.0} [Simply Conveyors] (SimplyConveyors-2.1.2.jar) 
	UCH	flammpfeil.slashblade{mc1.11-r8} [SlashBlade] (SlashBlade-mc1.11-r8.jar) 
	UCH	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.11-1.2a.jar) 
	UCH	stonehenge{1.10.2-0.1} [Stonehenge] (stonehenge-1.11.2-0.1.jar) 
	UCH	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.11-1.1.3.0.jar) 
	UCH	switchbow{1.0} [Switch-Bow] (switchbow-1.0.jar) 
	UCH	tammodized{0.6.2} [TamModized] (TamModized-1.11.2-0.6.2.jar) 
	UCH	telepads{1.11 v1.0.1.0} [Telepads] (telepads-1.11-v1.0.1.0.jar) 
	UCH	terraqueous{1.3.6} [Terraqueous] (terraqueous-1.11.0-1.3.6.jar) 
	UCH	terraria{36a} [Terraria Craft] (TerrariaCraft_1.11.2-36a.jar) 
	UCH	beneath{1.2.0} [The Beneath] (The Beneath-1.11.2-1.2.0.jar) 
	UCH	toroquest{1.11.2-3.2} [ToroQuest] (toroquest-1.11.2-3.2.jar) 
	UCH	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
	UCH	vanillamagic{1.11.2-0.21.9.1} [Vanilla Magic] (VanillaMagic-1.11.2-0.21.9.1.jar) 
	UCH	vanillamagicaddon{1.11.2-0.21.9.v1} [Vanilla Magic Addon] (VanillaMagicAddon-1.11.2-0.21.9.v1.jar) 
	UCH	variedcommodities{1.11.2} [Varied Commodities] (VariedCommodities_1.11.2(22jan17).jar) 
	UCH	visiblearmorslots{3.1.1} [Visible Armor Slots] (VisibleArmorSlots[1.11.2]-3.1.1.jar) 
	UCH	voidcraft{0.16.1} [VoidCraft] (VoidCraft-1.11.2-0.16.1.jar) 
	UCH	waddles{0.5.1} [Waddles] (Waddles-1.11-0.5.1.jar) 
	UCH	wasteland_meteors{1.11-0.1} [Wasteland Meteors] (wasteland_meteors-1.11-0.1.jar) 
	UCH	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	Loaded coremods (and transformers): 
MuonPlugin (muon-0.1.jar)
  gd.izno.mc.muon.MuonClassTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  brad16840.common.asm.ClassTransformer
GudLib (gud_lib-1.1.0.2.jar)
  net.gudenau.lib.core.ClientTransformer
ForgelinPlugin (Forgelin-1.4.0.jar)
  
PotionCoreFMLLoadingPlugin (PotionCore-1.4_for_1.11.2.jar)
  com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  lumien.randomthings.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
TerrariaCraftCore (TerrariaCraft_1.11.2-36a.jar)
  com.mrdimka.terraria.core.TerrariaCraftASM
LoadingPlugin (CrystalMod-1.11.2-4.5.0dev.jar)
  alec_wam.CrystalMod.asm.ClassTransformer
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
literalascension (literalascension-1.11.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
IvToolkit (IvToolkit-1.3.2.1.jar)
  
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-83.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6530D'

**Comment by lumien231** [comment]
Can you reproduce this with only Random Things installed?

**Comment by border999** [comment]
I'm getting this crash now a few years later, I'm assuming some invalid mod interaction

**Comment by border999** [comment]
seems like it doesn't like a mod called Gosyn, when I crashed.
