### ISSUE TITLE
Crash in debug world (Runebase Block)

### ISSUE THREAD

**Issue by ThomasAunvik** [lumien231/Random-Things#202]
So, i went around in debug mode and i crashed, what i got from what this block: `randomthings:runebase`
Here is the full crashlog
[Crash Log](https://pastebin.com/F8rWazYv)

**Comment by lumien231** [comment]
Can you reproduce this with only Random Things installed?

**Comment by ThomasAunvik** [comment]
Sure, i tested this on v3.8.1 1.11.2.
[Crash Log](https://pastebin.com/gzVHmM5b)

```
java.lang.NullPointerException: Tesselating block model
    at lumien.randomthings.client.models.blocks.ModelRune.func_188616_a(ModelRune.java:76)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:129)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
    at java.lang.Thread.run(Thread.java:745)
```

This is what happened when i did /give Thaun_ `randomthings:runebase` .
It gave me `tile.runebase.name`. I could place it down, but it was weird beacuse it did not render anything.

In the second image i placed the runebase ontop of a runbase.

![Imgur](http://i.imgur.com/4j5028c.png)
![Imgur](http://i.imgur.com/aZGyyKq.png)

**Comment by lumien231** [comment]
Yeah, you aren't meant to get that block as an item, will remove the item next version so you can't get it anymore.
