### ISSUE TITLE
[1.8-3.5.4] Bug report on startup in 1.8 pack

### ISSUE THREAD

**Issue by Lythom** [lumien231/Random-Things#22]
RandomThings 1.8-3.5.4 crashes server on startup.
Forge version : 11.14.3.1512

My pack doesn't need absolutely RandomThings, but it's always better when it works :)
If you need further actions or testing let me know.

Full report :

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  LoadingPlugin (RandomThings-MC1.8-3.5.4.jar)
  BetterFoliageLoader (BetterFoliage-mc1.8-1.1.6.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1099-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 03/09/15 20:44
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ExceptionInInitializerError
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:553)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:413)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ExceptionInInitializerError
    at lumien.randomthings.RandomThings.preInit(RandomThings.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
    ... 10 more
Caused by: java.lang.RuntimeException: That channel is already registered
    at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:146)
    at lumien.randomthings.network.RandomThingsNetworkWrapper.<init>(RandomThingsNetworkWrapper.java:35)
    at lumien.randomthings.network.PacketHandler.<clinit>(PacketHandler.java:10)
    ... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 385422952 bytes (367 MB) / 1445986304 bytes (1379 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1512 57 mods loaded, 57 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1512.jar) 
    UCH Forge{11.14.3.1512} [Minecraft Forge] (forge-1.8-11.14.3.1512.jar) 
    UCH Aroma1997Core{1.0.3.4} [Aroma1997Core] (Aroma1997Core-1.8-1.0.3.4.jar) 
    UCH CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
    UCH NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCH VeinMiner_coremod{0.26.1_build.unknown} [Core mod] (minecraft.jar) 
    UCH BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1099-universal.jar) 
    UCH arrowcam{1.1} [Arrow Camera] (1.8_arrowcam_v1.2.jar) 
    UCH securitycraft{v1.7.4.1} [SecurityCraft] ([1.8] SecurityCraft v1.7.4.1.jar) 
    UCH bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
    UCH ArmorStatusHUD{1.8} [ArmorStatusHUD] ([1.8]ArmorStatusHUD-client-1.29.jar) 
    UCH CrystalWing{1.8.r01} [CrystalWing] ([1.8]CrystalWing-universal-1.8.r01.jar) 
    UCH StatusEffectHUD{1.8} [StatusEffectHUD] ([1.8]StatusEffectHUD-client-1.27.jar) 
    UCH animalbikes{1.8} [Animal Bikes] (AnimalBikes_1.8.0.jar) 
    UCH antiqueatlas{4.2.7-1.8} [Antique Atlas] (antiqueatlas-4.2.7-1.8.jar) 
    UCH Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper] (Aroma1997Core-1.8-1.0.3.4.jar) 
    UCH AromaBackup{0.0.1.0} [AromaBackup] (AromaBackup-1.8-0.0.1.0.jar) 
    UCH iChunUtil{5.4.0} [iChunUtil] (iChunUtil-5.4.0.jar) 
    UCH BackTools{5.1.0} [BackTools] (BackTools-5.1.0.jar) 
    UCH Baubles{1.1.1.0} [Baubles] (Baubles-1.8-1.1.1.0.jar) 
    UCH BetterFoliage{1.1.6} [Better Foliage] (BetterFoliage-mc1.8-1.1.6.jar) 
    UCH AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8-1.4.0-1.jar) 
    UCH C4Lib{1.0.0} [C4Lib] (C4Lib-1.8-1.0.0-universal.jar) 
    UCH capsule{1.0.1} [Capsule] (capsule-1.8-1.0.1.jar) 
    UCH Chameleon{1.8-0.1.0} [Chameleon] (Chameleon-1.8-0.1.0.jar) 
    UCH chisel{@VERSION@} [Chisel 3] (Chisel_DEV-MC1.8-0.0.1.3.jar) 
    UCH customnpcs{1.8.0_beta} [CustomNPCs] (CustomNPCs_1.8.0_beta.jar) 
    UCH cyclopscore{0.1.1} [Cyclops Core] (CyclopsCore-1.8-0.1.1.jar) 
    UCH evilcraft{0.8.1} [EvilCraft] (EvilCraft-1.8-0.8.1.jar) 
    UCH HelpFixer{1.1.9} [HelpFixer] (HelpFixer-1.1.9.jar) 
    UCH hopperducts{1.4.5} [Hopper Ducts] (hopperducts-mc1.8-1.4.5.jar) 
    UCH InfernalMobs{1.6.4} [Infernal Mobs] (InfernalMobs-1.8.jar) 
    UCH InventoryPets{Beta} [Inventory Pets] (inventorypets-1.8-beta.jar) 
    UCH inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
    UCH IronChest{6.0.99.749} [Iron Chest] (ironchest-1.8-6.0.99.749-universal.jar) 
    UCH lootplusplus{1.1.1_for_1.8} [Loot++] (Loot++-1.1.1_for_1.8.jar) 
    UCH RadixCore{1.8-2.0.5} [RadixCore] (RadixCore-1.8-2.0.5-universal.jar) 
    UCH MCA{1.8-5.0.7.1} [Minecraft Comes Alive] (MCA-1.8-5.0.7.1-universal.jar) 
    UCH moreplayermodels{1.8.0_beta} [MorePlayerModels] (MorePlayerModels_1.8.0_beta.jar) 
    UCH pandorasbox{2.1.2} [Pandora's Box] (PandorasBox-2.1.2.jar) 
    UCH parachutemod{3.1.1} [Parachute Mod] (parachutemod-1.8.0-3.1.2-96.jar) 
    UCH progressiveautomation{1.6.15} [Progressive Automation] (ProgressiveAutomation-1.8-1.6.15.jar) 
    UCH quickhotbar{1.04} [Quick Hotbar] (quickhotbar_18_1.04.jar) 
    UCH ragdollCorpses{0.12} [Ragdoll Corpses] (ragdollCorpses-0.12 for 1.8.jar) 
    UCE RandomThings{3.5.4} [Random Things] (RandomThings-MC1.8-3.5.4.jar) 
    UCH redstonepaste{1.7.1} [Redstone Paste] (redstonepaste-mc1.8-1.7.1.jar) 
    UCH Roguelike{1.3.6} [Roguelike Dungeons] (RoguelikeDungeons-1.8-1.3.6.jar) 
    UCH soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
    UCH StorageDrawers{1.8-2.1.9} [Storage Drawers] (StorageDrawers-1.8-2.1.9.jar) 
    UCH Talismans 2{2.1.2} [Talismans 2] (Talismans2-1.8-2.1.2.jar) 
    UCH ultimate_unicorn_mod{1.2.2} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.8-1.2.2.jar) 
    UCH VeinMiner{0.26.1_build.unknown} [Vein Miner] (VeinMiner-1.8_0.27.0.unknown.jar) 
    UCH VeinMinerModSupport{0.26.1_build.unknown} [Mod Support] (VeinMiner-1.8_0.27.0.unknown.jar) 
    UCH Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) 
    UCH wailafeatures{0.0.1} [WAILA Features] (WAILA-features-1.8-0.0.1.jar) 
    UCH denseores{1.0} [denseores] (denseores-2.(-1).0 (alpha 1.8).jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  portablejim.veinminer.asm.ItemInWorldManagerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
LoadingPlugin (RandomThings-MC1.8-3.5.4.jar)
  lumien.randomthings.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-mc1.8-1.1.6.jar)
  mods.betterfoliage.loader.impl.BetterFoliageTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)

NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1099-universal.jar)
  org.spongepowered.asm.mixin.transformer.MixinTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.52' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
```

**Comment by Bloodmorphed** [comment]
I would like to add this is just not on servers, it is crashing with this exact error on my client too.
