### ISSUE TITLE
1.12 server crash due to random things?

### ISSUE THREAD

**Issue by trilexcom** [lumien231/Random-Things#233]
hi Our Server crashed using 
Forge 2443
Random Things :  MC1.12-4.0.4

error : 

java.lang.Error
    at net.minecraft.util.math.Vec3i.hashCode(SourceFile:54)
    at java.util.HashMap.hash(HashMap.java:338)
    at java.util.HashMap.containsKey(HashMap.java:595)
    at java.util.HashSet.contains(HashSet.java:203)
    at lumien.randomthings.tileentity.redstoneinterface.TileEntityRedstoneInterface.getRedstonePower(TileEntityRedstoneInterface.java:107)
    at lumien.randomthings.handler.AsmHandler.getRedstonePower(AsmHandler.java:404)

Crashlog link : https://pastebin.com/PuA6ck9k

hi Lumien 

please let me know if its random things causing this error or another mod 

Thanks again 

Mat (TrilexCom)

**Comment by lumien231** [comment]
Is this reproducable or did this only happen once?

**Comment by trilexcom** [comment]
It only happend once

**Comment by krisjenner** [comment]
Same issue All The Mods 3 Remix modpack server running Sponge 7.1.5

https://gist.github.com/krisjenner/935f2902bbe9d88b2683fff8a95221ca
