### ISSUE TITLE
I can't login in minecraft

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#28]
[19:55:02] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[19:55:02] [main/INFO] [FML]: Forge Mod Loader version 7.99.32.1517 for Minecraft 1.7.10 loading
[19:55:02] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_60, running on Windows 7:x86:6.1, installed at C:\Program Files (x86)\Java\jre1.8.0_60
[19:55:02] [main/INFO] [FML]: [AppEng] Core Init
[19:55:02] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_C1.jar
[19:55:02] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/WARN] [FML]: The coremod portablejim.veinminer.asm.VeinMinerCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:55:02] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:55:02] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[19:55:02] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[19:55:02] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[19:55:02] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[19:55:02] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/USER/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_U_C1.jar
[19:55:02] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@14425a7
[19:55:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:55:04] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [IC2-core]: Loaded library ejml-0.23.jar.
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:55:04] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[19:55:04] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[19:55:04] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[19:55:04] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:55:05] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[19:55:05] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[19:55:05] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[19:55:05] [main/INFO] [RandomThingsCore]: Found World Class: net/minecraft/world/World
[19:55:05] [main/INFO]: Setting user: alxan_vance
[19:55:05] [main/INFO] [RandomThingsCore]: Found Item Class: net/minecraft/item/Item
[19:55:05] [main/INFO] [FastLeafDecay]: Patching leaves.
[19:55:05] [main/INFO] [FastLeafDecay]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[19:55:05] [main/INFO] [RandomThingsCore]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[19:55:05] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockOldLeaf
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockOldLeaf
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockLeaves
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeaves
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockLeavesBase
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeavesBase
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/block/BlockLeavesBase
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Exception in thread "main" [19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.SecurityManager.checkExit(Unknown Source)
[19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Runtime.exit(Unknown Source)
[19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.System.exit(Unknown Source)
[19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:55:05] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by lumien231** [comment]
Remove Fast Leaf Decay, it's included in Random Things 1.7.10.

**Comment by ProxyPlayerHD** [comment]
it should really say this in the description of the mod or atleast pop up some message when Fast Leaf Decay is also installed. like forge does when it notices 2 instances of the same mod being installed
