### ISSUE TITLE
Crash when generating Tropicraft chunk.

### ISSUE THREAD

**Issue by rvveber** [lumien231/Random-Things#315]
Hello lumien,
On our Server we get a crash caused by random things.
We are running spongeforge 2703-7.1.0-BETA-3124
on minecraft Forge 14.23.4.2703

Crash report:
```
Description: Exception ticking world

java.lang.ClassCastException: lumien.randomthings.biomes.BiomeSpectral cannot be cast to net.tropicraft.core.common.biome.BiomeTropicraft
	at net.tropicraft.core.common.dimension.ChunkProviderTropicraft.func_185931_b(ChunkProviderTropicraft.java:80)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:269)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bba000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

this happens in RandomThings 4.0.8(this crash report) aswell as the newest 4.1.8.

**Comment by lumien231** [comment]
Since there's no RandomThings in the stacktrace i'm guessing this is probably a sponge issues. Can you reproduce this with normal forge?

**Comment by rvveber** [comment]
It might be, i can't test it right now.

I'm not a fan of the spectre feature anyways, is there not a way to completely disable it altogether?
