### ISSUE TITLE
[COL] After updating to 4.2.1, LoaderExceptionModCrash

### ISSUE THREAD

**Issue by drakray** [lumien231/Random-Things#336]
https://pastebin.com/37vUva15

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at lumien.randomthings.item.ItemEnderBucket.getItemStackLimit(ItemEnderBucket.java:56)
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:248)
	at hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted(EnchantmentUpgradeHelper.java:182)
	at hellfirepvp.astralsorcery.common.enchantment.amulet.PlayerAmuletHandler.attachAmuletItemCapability(PlayerAmuletHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2218_PlayerAmuletHandler_attachAmuletItemCapability_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:667)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:649)
```

Conflicing wtih Astral Sorcery?

**Comment by drakray** [comment]
Might be CraftTweaker, as I found this in it's logFile

```
[POSTINITIALIZATION][CLIENT][ERROR] Error while applying actions
java.lang.NullPointerException
	at lumien.randomthings.item.ItemEnderBucket.getItemStackLimit(ItemEnderBucket.java:56)
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:248)
	at hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted(EnchantmentUpgradeHelper.java:182)
	at hellfirepvp.astralsorcery.common.enchantment.amulet.PlayerAmuletHandler.attachAmuletItemCapability(PlayerAmuletHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2218_PlayerAmuletHandler_attachAmuletItemCapability_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:667)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:649)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at crafttweaker.mc1120.item.MCItemStack.<init>(MCItemStack.java:56)
	at crafttweaker.api.minecraft.CraftTweakerMC.getIItemStack(CraftTweakerMC.java:136)
	at crafttweaker.mc1120.recipes.MCRecipeManager$ActionRemoveShapedRecipes.apply(MCRecipeManager.java:413)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:51)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:135)
	at java.util.ArrayList.forEach(Unknown Source)
	at crafttweaker.mc1120.CraftTweaker.onPostInit(CraftTweaker.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Ravalli03** [comment]
I'm also getting a crash after installing the mod

https://pastebin.com/0sTM5uQF

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/854#issuecomment-415996817

Further information.
