### ISSUE TITLE
After installing this mod, my survival world is PERM locked and cannot start anymore.

### ISSUE THREAD

**Issue by Fishwicks** [lumien231/Random-Things#447]
I tried to add this to my modded survival (1.14.4) and it just crashed with
---- Minecraft Crash Report ----
// You're mean.

Time: 9/7/19 10:34 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.<init>(Lnet/minecraft/fluid/Fluid;I)V
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackListFactory.lambda$create$1(FluidStackListFactory.java:23) ~[?:6.0.0.11] {}
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackListFactory$$Lambda$4300/569944732.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackListFactory.create(FluidStackListFactory.java:24) ~[?:6.0.0.11] {}
	at mezz.jei.plugins.vanilla.VanillaPlugin.registerIngredients(VanillaPlugin.java:135) ~[?:6.0.0.11] {}
	at mezz.jei.load.PluginLoader.lambda$new$1(PluginLoader.java:93) ~[?:6.0.0.11] {}
	at mezz.jei.load.PluginLoader$$Lambda$4296/465112397.accept(Unknown Source) ~[?:?] {}
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) ~[?:6.0.0.11] {}
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:93) ~[?:6.0.0.11] {}
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71) ~[?:6.0.0.11] {}
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:125) ~[?:6.0.0.11] {}
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:103) ~[?:6.0.0.11] {}
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$2834/1210897975.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2117/498618142.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:999) ~[?:?] {}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1265) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28) ~[?:?] {}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$4268/2026085942.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:857) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.49.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/1224064486.call(Unknown Source) [forge-1.14.4-28.0.49.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackListFactory.lambda$create$1(FluidStackListFactory.java:23)
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackListFactory$$Lambda$4300/569944732.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackListFactory.create(FluidStackListFactory.java:24)
	at mezz.jei.plugins.vanilla.VanillaPlugin.registerIngredients(VanillaPlugin.java:135)
	at mezz.jei.load.PluginLoader.lambda$new$1(PluginLoader.java:93)
	at mezz.jei.load.PluginLoader$$Lambda$4296/465112397.accept(Unknown Source)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:93)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71)
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:125)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:103)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$2834/1210897975.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2117/498618142.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:999)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1265)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at net.minecraft.network.PacketThreadUtil$$Lambda$4268/2026085942.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Fishwicks'/240, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 361, 0
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1745)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/1224064486.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 741554144 bytes (707 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.49.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.49
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		BiomesOPlenty-1.14.4-9.0.0.231-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.229 DONE}
		extragolems-9.0.1.jar Extra Golems {golems@TODO-golems_version DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		MoreOresInONE-1.3b.jar More Ores in ONE {moreoresinone@1.3b DONE}
		MrCrayfishs-Furniture-Mod-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre4 DONE}
		Nifty-Mod-1.14.4.jar Nifty {nifty@2.5 DONE}
		Random-Things-Mod-1.14.4.jar Random Things {randomthings@5.0 DONE}
		SuperTools-1.5b.jar Super Tools {supertools@1.5b DONE}
		Xaeros_Minimap_1.17.9_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.17.9 DONE}
		forge-1.14.4-28.0.49-universal.jar Forge {forge@28.0.49 DONE}
		forge-1.14.4-28.0.49-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.0.49
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6576, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Fomari's Discs, file/VanillaTweaks_r369174
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

But, if I remove mod, it requires me to have it. No matter what, I can't launch my world anymore. Please... please help me!!! :((((((((((((

**Comment by Fishwicks** [comment]
Update: might've been JEI.

**Comment by Fishwicks** [comment]
it was.
