### ISSUE TITLE
Crash in Spectre coil

### ISSUE THREAD

**Issue by Sekuraz** [lumien231/Random-Things#451]
On teleportation the game crashes with 

```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at lumien.randomthings.tileentity.TileEntitySpectreCoil.hasCapability(TileEntitySpectreCoil.java:65)
	at p455w0rdslib.capabilities.CapabilityLightEmitter.hasCap(CapabilityLightEmitter.java:47)
	at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:152)
	at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)
	at net.minecraft.client.renderer.RenderGlobal.func_174982_a(RenderGlobal.java:1133)
	at net.minecraft.client.renderer.RenderGlobal.func_174977_a(RenderGlobal.java:1125)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1328)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Sekuraz** [comment]
Saw the outdated other issue.
