### ISSUE TITLE
Crashes worldgen when world type is Garden of Glass

### ISSUE THREAD

**Issue by Josephur** [lumien231/Random-Things#53]
Have to temporarily disable Random-Things when generating a new Garden of Glass world, then re-enable when the world is created, not sure if this is a Garden of Glass issue or Random-Things issue, but it's easily repeatable.

Using the new 1.8.9 Botania.r1.8-248-MC1.8-0.6.1 / GardenOfGlass and RandomThings-MC1.8.9-3.6.2

**Comment by williewillus** [comment]
Is there a log?

**Comment by Josephur** [comment]
It would appear it's something to do with it placing Nature Cores?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-31.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.8.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 2/21/16 2:11 AM
Description: Exception initializing level

java.lang.NullPointerException: Exception initializing level
    at lumien.randomthings.worldgen.WorldGenCores.placeNatureCore(WorldGenCores.java:262)
    at lumien.randomthings.worldgen.WorldGenCores.generate(WorldGenCores.java:218)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1053)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at thaumcraft.common.lib.utils.BlockUtils.isBlockTouching(BlockUtils.java:361)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateOres(ThaumcraftWorldGenerator.java:288)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:312)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:65)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:53)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1039)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at thaumcraft.common.lib.utils.BlockUtils.isBlockTouching(BlockUtils.java:361)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateOres(ThaumcraftWorldGenerator.java:288)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:312)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:65)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:53)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at net.minecraft.world.World.func_175623_d(World.java:204)
    at net.minecraft.world.World.func_175703_c(World.java:189)
    at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:64)
    at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:844)
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:766)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:89)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at java.lang.Thread.run(Unknown Source)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at lumien.randomthings.worldgen.WorldGenCores.placeNatureCore(WorldGenCores.java:262)
    at lumien.randomthings.worldgen.WorldGenCores.generate(WorldGenCores.java:218)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1053)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at thaumcraft.common.lib.utils.BlockUtils.isBlockTouching(BlockUtils.java:361)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateOres(ThaumcraftWorldGenerator.java:288)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:312)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:65)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:53)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1039)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at thaumcraft.common.lib.utils.BlockUtils.isBlockTouching(BlockUtils.java:361)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateOres(ThaumcraftWorldGenerator.java:288)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:312)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:65)
    at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:53)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at net.minecraft.world.World.func_175623_d(World.java:204)
    at net.minecraft.world.World.func_175703_c(World.java:189)
    at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:64)
    at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:844)

-- Affected level --
Details:
    Level name: MyGlassWorld
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 1006 Drop: 0
    Level seed: 1629188324667095803
    Level generator: ID 07 - botania-skyblock, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:766)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:89)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2072873784 bytes (1976 MB) / 3325034496 bytes (3171 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1756 84 mods loaded, 84 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAA FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1756.jar) 
    UCHIJAA Forge{11.15.1.1756} [Minecraft Forge](forge-1.8.9-11.15.1.1756.jar) 
    UCHIJAA Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAA aura{591} [Aura Cascade](AuraCascade-591.jar) 
    UCHIJAA bagginses{2.1.5b} [Bagginses](Bagginses-1.8.9-2.1.5b.jar) 
    UCHIJAA BetterAchievements{0.1.1} [Better Achievements](BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAA BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies](BetterThanBunnies-1.8.9-1.0.1.jar) 
    UCHIJAA BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1922-universal.jar) 
    UCHIJAA Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAA intangible{0.0.23} [Intangible](intangible-1.8.9-0.0.23.jar) 
    UCHIJAA JEI{2.28.1.161} [Just Enough Items](jei_1.8.9-2.28.1.161.jar) 
    UCHIJAA BloodMagic{1.8.9-2.0.0-18} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-18.jar) 
    UCHIJAA bookshelfapi{2.3.2} [Bookshelf](Bookshelf-1.8.9-2.3.2.jar) 
    UCHIJAA Thaumcraft{5.1.6} [Thaumcraft](Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAA Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-0.6.1.jar) 
    UCHIJAA BuildCraft|Core{7.2.0-pre11} [BuildCraft](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA BuildCraft|Transport{7.2.0-pre11} [BC Transport](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA BuildCraft|Factory{7.2.0-pre11} [BC Factory](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA BuildCraft|Silicon{7.2.0-pre11} [BC Silicon](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA BuildCraft|Robotics{7.2.0-pre11} [BC Robotics](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA BuildCraft|Energy{7.2.0-pre11} [BC Energy](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA BuildCraft|Builders{7.2.0-pre11} [BC Builders](buildcraft-7.2.0-pre11.jar) 
    UCHIJAA buildingbrickscompatvanilla{1.8.9-1.3.2} [Building Bricks Vanilla Compat](BuildingBricks-1.8.9-1.3.2.jar) 
    UCHIJAA buildingbricks{1.8.9-1.3.2} [Building Bricks](BuildingBricks-1.8.9-1.3.2.jar) 
    UCHIJAA Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAA mcmultipart{1.0.7} [MCMultiPart](MCMultiPart-1.0.7-universal.jar) 
    UCHIJAA CharsetLib{0.2.1} [‽](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA CharsetTweaks{0.2.1} [*](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA CharsetWires{0.2.1} [+](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA CharsetAudio{0.2.1} [♫](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA CharsetStorage{0.2.1} [#](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA CharsetPipes{0.2.1} [|](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA CharsetGates{0.2.1} [&](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAA chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAA chiselsandbits{mc1.8.9-v1.8.10} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.10.jar) 
    UCHIJAA compasscoords{1.8.9-0.2.6} [Compass Co-ords](CompassCoords-1.8.9-0.2.6.jar) 
    UCHIJAA ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
    UCHIJAA craftingtweaks{3.0.41} [Crafting Tweaks](craftingtweaks-mc1.8.9-3.0.41.jar) 
    UCHIJAA crafttweaker{3.0.0} [crafttweaker](CraftTweaker-Customized-1.8.8-3.0.1.jar) 
    UCHIJAA CustomMainMenu{2.0} [Custom Main Menu](CustomMainMenu-MC1.8.9-2.0.jar) 
    UCHIJAA dsurround{2.0.4.10} [Dynamic Surroundings](DynamicSurroundings-1.8.9-2.0.4.10.jar) 
    UCHIJAA ShetiPhianCore{3.1.0} [ShetiPhian-Core](ShetiPhianCore-1.8.9-3.1.0.jar) 
    UCHIJAA EnderTanks{1.2.1} [EnderTanks](EnderTanks-1.8.9-1.2.1.jar) 
    UCHIJAA exnihilo2{0.28} [Ex Nihilo 2](ExNihilo2-0.28.jar) 
    UCHIJAA ezstorage{1.0} [EZ Storage](ezstorage-1.8.9-1.2.4.jar) 
    UCHIJAA fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.8-1.6.jar) 
    UCHIJAA flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.6.jar) 
    UCHIJAA FTBL{2.0.2} [FTBLib](FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAA FTBU{2.0.2} [FTBUtilities](FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAA furnus{1.7} [Furnus](Furnus-1.8.9-1.7.jar) 
    UCHIJAA GardenOfGlass{sqrt(-1)} [Garden of Glass](GardenOfGlass.jar) 
    UCHIJAA graves{1.8.9-b39-universal} [Graves Mod](graves-1.8.9-b39-universal.jar) 
    UCHIJAA hopperducts{1.4.6} [Hopper Ducts](hopperducts-mc1.8.8-1.4.6.jar) 
    UCHIJAA k4lib{1.8.9-1.0.16} [K4Lib](k4lib-1.8.9-1.0.16-universal.jar) 
    UCHIJAA HydCraft{1.8.9-3.1.65} [Hydraulicraft](HydCraft-1.8.9-3.1.65-universal.jar) 
    UCHIJAA IGWMod{1.2.3-3} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.3-3-universal.jar) 
    UCHIJAA inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAA inventorytweaks{1.60-beta-31-0aadb96} [Inventory Tweaks](InventoryTweaks-1.60-beta-31.jar) 
    UCHIJAA IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAA JEIAddons{0.12.0.57} [Just Enough Items Addons](JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAA journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAA jeresources{0.3.4} [Just Enough Resources](JustEnoughResources-1.8.9-0.3.4.jar) 
    UCHIJAA llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
    UCHIJAA mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJAA testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAA MoreFurnaces{1.5.0} [More Furnaces](MoreFurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAA Morpheus{1.8.9-2.0.58} [Morpheus](Morpheus-1.8.9-2.0.58.jar) 
    UCHIJAA MouseTweaks{2.6.0} [Mouse Tweaks](MouseTweaks-2.6.0-mc1.8.9.jar) 
    UCHIJAA neotech{2.3.7} [NeoTech](NeoTech-1.8.9-2.3.7.jar) 
    UCHIJAA fodc{1.7.2} [Ore Dictionary Converter](OreDictionaryConverter-1.7.2.jar) 
    UCHIJAA playerrugs{0.0.1} [Player Rugs](PlayerRugs-1.8.8-1.2.0.jar) 
    UCHIJAA PneumaticCraft{1.13.6} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.6-universal.jar) 
    UCHIJAA progressiveautomation{1.6.35} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAA Psi{beta-14} [Psi](Psi-beta-14.jar) 
    UCHIJAA RandomThings{3.6.2} [Random Things](RandomThings-MC1.8.9-3.6.2.jar) 
    UCHIJAA ResourceLoader{1.4} [Resource Loader](ResourceLoader-MC1.8.8-1.4.jar) 
    UCHIJAA rftools{4.22beta22} [RFTools](rftools-1.8.9-4.22beta22.jar) 
    UCHIJAA Roguelike{1.4.5} [Roguelike Dungeons](RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAA simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAA StorageDrawers{1.8.9-2.4.1} [Storage Drawers](StorageDrawers-1.8.9-2.4.1.jar) 
    UCHIJAA tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAA thaumicinfusion{4.8} [Thaumic Infusion](ThaumicInfusion-1.8.9-4.8.jar) 
    UCHIJAA wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-beta-31.jar)
  invtweaks.forge.asm.ContainerTransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.8.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
Profiler Position: N/A (disabled)
Player Count: 0 / 8; []
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```
