### ISSUE TITLE
Crash issue due to change in forge

### ISSUE THREAD

**Issue by Entoarox** [lumien231/Random-Things#64]
The following crash occurs when using forge **1.9-12.16.0.1809** to load the mod:

```
[09:47:29] [Client thread/ERROR] [FML]: Caught exception from randomthings
java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.findUniqueIdentifierFor(Lnet/minecraft/block/Block;)Lnet/minecraftforge/fml/common/registry/GameRegistry$UniqueIdentifier;
    at lumien.randomthings.client.models.ItemModels.registerBlock(ItemModels.java:145) ~[ItemModels.class:?]
    at lumien.randomthings.client.models.ItemModels.register(ItemModels.java:17) ~[ItemModels.class:?]
    at lumien.randomthings.client.ClientProxy.registerModels(ClientProxy.java:149) ~[ClientProxy.class:?]
    at lumien.randomthings.RandomThings.preInit(RandomThings.java:82) ~[RandomThings.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.9-12.16.0.1809-1.9.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221) ~[forge-1.9-12.16.0.1809-1.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:199) ~[forge-1.9-12.16.0.1809-1.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:128) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434) [bcf.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346) [bcf.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by Entoarox** [comment]
Ty! :smile:
