### ISSUE TITLE
[1.10] Breaking Prismarine Ender Bridge/Ender Bridge

### ISSUE THREAD

**Issue by Spidi** [lumien231/Random-Things#94]
forge-1.10-12.18.0.1996-1.10.0

breaking any type of ender bridge crashes the client with the following error:

`java.lang.NoSuchMethodError: net.minecraft.block.BlockDispenser.func_149937_b(I)Lnet/minecraft/util/EnumFacing;
    at lumien.randomthings.block.BlockPrismarineEnderBridge.func_176203_a(BlockPrismarineEnderBridge.java:105)
    at net.minecraft.client.renderer.RenderGlobal.func_180439_a(RenderGlobal.java:2342)
    at net.minecraft.world.World.func_180498_a(World.java:3633)
    at net.minecraft.world.World.func_175718_b(World.java:3624)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187103_a(PlayerControllerMP.java:152)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_180512_c(PlayerControllerMP.java:313)
    at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1421)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2198)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by lumien231** [comment]
Guess i have to make a 1.10 update after all ^^.
